import Link from 'next/link';
import { ArrowRight, ArrowUpRight, MapPin, Clock3, Phone, ShoppingBag, Leaf, ChefHat, Heart, BadgeIndianRupee, UtensilsCrossed, Star } from 'lucide-react';
import { restaurantConfig as r } from '@/config/restaurant';
import { reviews } from '@/data/reviews';
import { FoodImage } from '@/components/food-card/food-image';
import { Button } from '@/components/ui-kit';
import { ContactAction } from '@/components/sections/contact-action';

export const SectionHeading = ({ eyebrow, title, description, centered = false }: { eyebrow: string; title: string; description?: string; centered?: boolean }) => {
  return <div className={centered ? 'mx-auto max-w-2xl text-center' : ''}><p className="mb-3 text-[10px] font-semibold uppercase tracking-[0.18em] text-primary">{eyebrow}</p><h2 className="whitespace-pre-line font-serif text-[clamp(2.05rem,3.3vw,3.1rem)] font-medium leading-[1.18] tracking-[-0.035em]">{title}</h2>{description && <p className={`mt-4 max-w-lg text-[13px] leading-7 text-muted-foreground ${centered ? 'mx-auto' : ''}`}>{description}</p>}</div>;
};

export const QuickActions = () => {
  return <section aria-label="Quick actions" className="border-b border-border"><div className="container grid max-w-7xl grid-cols-3 px-5 py-5 sm:px-8"><Link href="/menu" className="flex items-center justify-center gap-2.5 border-r border-border text-[11px] font-medium transition-colors hover:text-primary sm:gap-4 sm:text-sm"><ShoppingBag size={18} strokeWidth={1.5} className="text-primary" /><span>Explore & order</span><ArrowUpRight size={13} className="hidden sm:block" /></Link><ContactAction kind="phone" className="flex items-center justify-center gap-2.5 border-r border-border text-[11px] font-medium transition-colors hover:text-primary sm:gap-4 sm:text-sm"><Phone size={17} strokeWidth={1.5} className="text-primary" /><span>Call us</span><ArrowUpRight size={13} className="hidden sm:block" /></ContactAction><ContactAction kind="maps" className="flex items-center justify-center gap-2.5 text-[11px] font-medium transition-colors hover:text-primary sm:gap-4 sm:text-sm"><MapPin size={18} strokeWidth={1.5} className="text-primary" /><span>Find us</span><ArrowUpRight size={13} className="hidden sm:block" /></ContactAction></div></section>;
};

export const StorySection = ({ full = false }: { full?: boolean }) => {
  return <section id="our-story" className="scroll-mt-28 bg-secondary/50"><div className="container grid max-w-7xl items-center gap-12 px-5 py-20 sm:px-8 lg:grid-cols-[1fr_1fr] lg:gap-24 lg:py-24">
    <div className="relative pb-6 pr-5 sm:pr-10"><div className="relative aspect-[1.1] overflow-hidden rounded-lg"><FoodImage src={r.storyImage} alt="Chicken karahi being cooked in a traditional pan, finished with fresh herbs" fill sizes="(max-width: 1024px) 90vw, 550px" /></div><div className="absolute bottom-0 right-0 flex size-28 flex-col items-center justify-center rounded-sm bg-primary p-4 text-center text-primary-foreground sm:size-36"><ChefHat size={31} strokeWidth={1.1} /><span className="mt-3 font-serif text-lg leading-tight sm:text-xl">Desi roots.<br />Honest food.</span></div></div>
    <div><SectionHeading eyebrow={r.content.story.eyebrow} title={r.content.story.title} /><div className="mt-6 space-y-4">{r.content.story.paragraphs.map((text) => <p key={text} className="text-[13px] leading-[1.95] text-muted-foreground">{text}</p>)}</div><p className="mt-7 flex items-center gap-2 font-serif text-xl italic text-primary"><Heart size={17} strokeWidth={1.3} />{r.content.story.signature}</p>{!full && <Link href="/about" className="mt-7 inline-flex items-center gap-5 border-b border-primary/40 pb-1.5 text-xs font-semibold text-primary">A little more about us <ArrowUpRight size={15} /></Link>}{r.demo && full && <p className="mt-7 rounded-md border border-border p-4 text-xs leading-6 text-muted-foreground">This is illustrative brand storytelling for an independent website concept, not a verified history of the restaurant.</p>}</div>
  </div></section>;
};

export const WhyUs = () => {
  return <section className="container max-w-7xl px-5 py-16 sm:px-8 lg:py-20"><SectionHeading centered eyebrow="THE LITTLE THINGS THAT MATTER" title="Good food. No shortcuts." /><div className="mt-10 grid grid-cols-2 gap-x-7 gap-y-9 lg:grid-cols-4">{[
    { icon: Leaf, title: 'Fresh ingredients', description: 'Thoughtfully chosen ingredients, prepared fresh in our kitchen.' },
    { icon: ChefHat, title: 'Authentic taste', description: 'Familiar Pakistani flavors, with heart in every recipe.' },
    { icon: Heart, title: 'Honest value', description: 'Generous portions and satisfying meals for the whole table.' },
    { icon: UtensilsCrossed, title: 'Warm hospitality', description: 'A friendly welcome, whether you stay a while or take it home.' },
  ].map((point) => <div key={point.title} className="text-center"><point.icon size={29} strokeWidth={1.2} className="mx-auto mb-4 text-primary" /><h3 className="text-sm font-semibold">{point.title}</h3><p className="mx-auto mt-2 max-w-56 text-xs leading-6 text-muted-foreground">{point.description}</p></div>)}</div></section>;
};

export const ReviewsSection = () => {
  return <section id="reviews" className="scroll-mt-28 border-y border-border bg-secondary/40"><div className="container max-w-7xl px-5 py-20 sm:px-8"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><SectionHeading eyebrow="AROUND OUR TABLE" title="Good food gets people talking." /><ContactAction kind="reviews" className="inline-flex items-center gap-3 self-start border-b border-foreground/30 pb-1.5 text-xs font-medium sm:self-auto">See all reviews <ArrowUpRight size={15} /></ContactAction></div><p className="mt-4 text-[11px] text-muted-foreground">Sample testimonials for this concept — not verified customer reviews.</p><div className="mt-8 grid gap-5 md:grid-cols-3">{reviews.map((review) => <article key={review.id} className="flex flex-col rounded-lg border border-border bg-card p-6 lg:p-8"><div aria-label={`${review.rating} out of 5 stars, sample rating`} className="flex gap-1">{Array.from({ length: review.rating }, (_, index) => <Star key={index} size={13} className="fill-primary text-primary" />)}</div><blockquote className="mb-7 mt-5 flex-1 font-serif text-[17px] leading-[1.8]">“{review.quote}”</blockquote><div className="flex items-center gap-3 border-t border-border pt-5"><span className="flex size-9 items-center justify-center rounded-full bg-secondary text-[10px] font-semibold">{review.initials}</span><div><p className="text-xs font-semibold">{review.name}</p><p className="mt-1 text-[10px] text-muted-foreground">{review.date}</p></div><span className="ml-auto rounded-sm border border-border px-1.5 py-0.5 text-[8px] uppercase tracking-wider text-muted-foreground">Demo</span></div></article>)}</div></div></section>;
};

export const LocationSection = ({ page = false }: { page?: boolean }) => {
  return <section id="location" className="scroll-mt-28 bg-secondary/50"><div className="container grid max-w-7xl gap-10 px-5 py-20 sm:px-8 lg:grid-cols-[0.9fr_1.1fr] lg:gap-20">
    <div><SectionHeading eyebrow="RIGHT HERE IN YOUR NEIGHBORHOOD" title="Follow the flavor." description={`Come by for a meal, leave with a memory. Find us in ${r.locality}, ${r.city}.`} /><div className="mt-7 space-y-5"><div className="flex gap-3"><MapPin size={19} strokeWidth={1.5} className="mt-1 shrink-0 text-primary" /><div><h3 className="text-xs font-semibold">Find your way to us</h3><p className="mt-1.5 text-xs leading-6 text-muted-foreground">{r.address}</p>{r.demo && <p className="mt-1 text-[10px] text-muted-foreground">Exact street address and map pin awaiting confirmation</p>}</div></div><div className="flex gap-3"><Clock3 size={19} strokeWidth={1.5} className="mt-1 shrink-0 text-primary" /><div><h3 className="text-xs font-semibold">There’s always time for good food</h3>{r.business.openingHours.map((hours) => <p key={hours.days} className="mt-1.5 text-xs leading-6 text-muted-foreground">{hours.days} <span className="mx-1.5">·</span> {hours.hours}</p>)}{r.business.openingHours.some((hours) => !hours.verified) && <p className="mt-1 text-[10px] text-muted-foreground">Demo hours · Please confirm before visiting</p>}</div></div></div><div className="mt-7 flex flex-wrap gap-3"><ContactAction kind="maps" className="inline-flex h-11 items-center justify-center gap-4 rounded-md bg-primary px-5 text-xs font-medium text-primary-foreground transition-colors hover:bg-primary/90">Get Directions <ArrowUpRight size={16} /></ContactAction><ContactAction kind="phone" className="inline-flex h-11 items-center justify-center gap-3 rounded-md border border-foreground/20 px-5 text-xs font-medium transition-colors hover:bg-secondary"><Phone size={14} />Call us</ContactAction></div></div>
    <div className="relative min-h-[355px] overflow-hidden rounded-lg border border-border bg-muted" aria-label={`Illustrative neighborhood graphic for ${r.locality}. Not an exact map.`}>
      <div aria-hidden="true" className="absolute inset-0 opacity-60"><div className="absolute -left-10 top-[20%] h-4 w-[120%] -rotate-[22deg] border-y border-border bg-card" /><div className="absolute -left-10 top-[75%] h-6 w-[120%] -rotate-[22deg] border-y border-border bg-card" /><div className="absolute left-[28%] top-[-20%] h-[150%] w-5 rotate-[18deg] border-x border-border bg-card" /><div className="absolute left-[75%] top-[-20%] h-[150%] w-8 rotate-[18deg] border-x border-border bg-card" /><div className="absolute left-1/2 top-[-20%] h-[150%] w-2 rotate-[18deg] bg-card" /><div className="absolute -left-10 top-[48%] h-3 w-[120%] -rotate-[22deg] bg-card" /><div className="absolute bottom-9 left-10 h-16 w-20 -rotate-[22deg] rounded-lg bg-primary/5" /><div className="absolute right-12 top-10 h-20 w-24 -rotate-[22deg] rounded-lg bg-primary/5" /></div>
      <div className="absolute inset-0 flex flex-col items-center justify-center p-6 text-center"><span className="flex size-16 items-center justify-center rounded-full border-[6px] border-primary/15 bg-primary text-primary-foreground shadow-editorial"><MapPin size={27} strokeWidth={1.6} /></span><div className="mt-4 rounded-md border border-border bg-card px-7 py-4 shadow-editorial"><p className="font-serif text-xl">{r.name}</p><p className="mt-1.5 text-[10px] text-muted-foreground">{r.locality}, {r.city}</p></div></div><span className="absolute bottom-4 left-4 right-4 text-center text-[9px] tracking-wide text-muted-foreground">NEIGHBORHOOD PREVIEW · NOT AN EXACT MAP</span>
    </div>
  </div></section>;
};

export const FinalCta = () => {
  return <section className="relative overflow-hidden bg-primary text-primary-foreground"><div aria-hidden="true" className="absolute -right-20 -top-28 size-[450px] rounded-full border border-primary-foreground/15" /><div aria-hidden="true" className="absolute -right-10 -top-20 size-[450px] rounded-full border border-primary-foreground/10" /><div className="container relative flex max-w-7xl flex-col justify-between gap-8 px-5 py-16 sm:px-8 lg:flex-row lg:items-center lg:py-20"><div><p className="mb-4 text-[10px] font-medium tracking-[0.2em] text-primary-foreground/80">YOUR TABLE. YOUR FAVORITES.</p><h2 className="whitespace-pre-line font-serif text-[clamp(3rem,5vw,4.3rem)] leading-[1.05] tracking-[-0.04em]">{r.content.finalCta.title}</h2><p className="mt-5 max-w-md text-sm leading-7 text-primary-foreground/80">{r.content.finalCta.description}</p></div><div className="flex flex-col items-start gap-4"><Link href="/menu" className="inline-flex h-14 items-center justify-center gap-10 rounded-md bg-background px-7 text-sm font-semibold text-foreground transition-transform hover:-translate-y-0.5">Let’s eat <ArrowUpRight size={18} /></Link><span className="text-[10px] text-primary-foreground/80">Dine in. Take away. Make a memory.</span></div></div></section>;
};
